chat:
  type: "group"
  title: "毕业一群"
  self: "protagnist"
  groupInfo:
    name: "毕业一群(500)"
    avatar: "https://picsum.photos/seed/group2/100/100"
    members: ["protagnist", "student1", "student2", "Zack"]
