users:
  protagonist:
    name: "奋斗的西瓜"
    avatar: "https://picsum.photos/seed/protagonist/100/100"
    bio: "新人独立游戏开发者，求关注!"
  sister:
    name: "姐姐"
    avatar: "https://picsum.photos/seed/sister/100/100"
    bio: "无"
  zhou_police:
    name: "周警官"
    avatar: "https://picsum.photos/seed/policeman/100/100"
    bio: "无"
  coat_man:
    name: "风衣男"
    avatar: "https://picsum.photos/seed/weiredpoliceman/100/100"
    bio: "无"
  neighbour1:
    name: "803"
    avatar: "https://picsum.photos/seed/neighbour1/100/100"
    bio: "living the moment"
  neighbour2:
    name: "603"
    avatar: "https://picsum.photos/seed/neighbour2/100/100"
    bio: "不服就干"
  neighbour3:
    name: "904"
    avatar: "https://picsum.photos/seed/neighbour3/100/100"
    bio: "喜欢清晨的阳光啊"
  admin:
    name: "物业小雅"
    avatar: "https://picsum.photos/seed/admin/100/100"
    bio: "竭诚为您服务"
  user1:
    name: "风海(群主)-十年独立恐怖游戏开发"
    avatar: "https://picsum.photos/seed/user1/100/100"
    bio: "热衷于收集各种都市传说，民间传说。然后做成游戏"
  user2:
    name: "巧盒-新人独立游戏开发者"
    avatar: "https://picsum.photos/seed/user2/100/100"
    bio: "肉鸽类游戏摸索中"
  user3:
    name: "秀栽-独立新游推广中"
    avatar: "https://picsum.photos/seed/user3/100/100"
    bio: "最新大作，77号远征队绝赞试玩中"
  student1:
    name: "首朱"
    avatar: "https://picsum.photos/seed/stu1/100/100"
    bio: "人生豪迈，重头再来"
  student2:
    name: "海飞"
    avatar: "https://picsum.photos/seed/stu2/100/100"
    bio: "不要温和地走进那个良夜"
  student3: 
    name: "Zack"
    avatar: "https://picsum.photos/seed/stu2/100/100"
    bio: "新公司火力全开中，HC无限"


    


